# Documentation:
# https://github.com/brigade/scss-lint/blob/master/lib/scss_lint/linter/README.md
linters:
  BorderZero:
    enabled: false
  ColorKeyword:
    enabled: false
  ColorVariable:
    enabled: false
  Comment:
    enabled: true
    allowed: '\* Note\: '
  DeclarationOrder:
    enabled: false
  DuplicateProperty:
    enabled: false
  ElsePlacement:
    enabled: false
  EmptyLineBetweenBlocks:
    enabled: false
  EmptyRule:
    enabled: false
  ExtendDirective:
    enabled: true
    severity: error
  FinalNewline:
    enabled: false
  HexNotation:
    enabled: false
  IdSelector:
    enabled: false
  ImportPath:
    enabled: false
  ImportantRule:
    enabled: true
  Indentation:
    enabled: false
  LeadingZero:
    enabled: true
    style: include_zero
  MergeableSelector:
    enabled: false
  NameFormat:
    enabled: false
  NestingDepth:
    enabled: false
  PlaceholderInExtend:
    enabled: false
  PropertySortOrder:
    enabled: false
  QualifyingElement:
    enabled: false
  SelectorDepth:
    enabled: false
  SelectorFormat:
    enabled: false
  Shorthand:
    enabled: false
  SingleLinePerSelector:
    enabled: false
  SpaceAfterComma:
    enabled: false
  SpaceAfterPropertyColon:
    enabled: true
    style: one_space_or_newline
  SpaceAroundOperator:
    enabled: false
  SpaceBeforeBrace:
    enabled: true
    allow_single_line_padding: true
  StringQuotes:
    enabled: false
  TrailingSemicolon:
    enabled: true
  UnnecessaryParentReference:
    enabled: false
  UrlQuotes:
    enabled: false
  VendorPrefix:
    enabled: false
  ZeroUnit:
    enabled: true
