status: 'dev-ready'
flavors:
  - automatic-sizing
  - manual-sizing
  - containers
  - horizontal-alignment-center
  - horizontal-alignment-space
  - horizontal-alignment-spread
  - horizontal-alignment-end
  - vertical-alignment-center
  - vertical-alignment-end
  - vertical-alignment-item
  - vertical-stretch
  - alignment-item-bump
  - order
dependencies:
  - helpers/sizing
